package iso3166

import "testing"

func TestDecode(t *testing.T) {

	tests := []struct {
		Country     string
		Region      string
		Expected    string
		ExpectError bool
	}{
		{"GB", "", "United Kingdom", false},

		{"GB", "CHS", "Cheshire", false},
		{"GB", "NTT", "Nottinghamshire", false},
		{"GB", "ESS", "Essex", false},
		{"GB", "ESX", "East Sussex", false},
		{"GB", "SEX", "", true},
		{"", "", "", true},
		{"", "CHS", "", true},

		{"GB", "ABC", "Armagh, Banbridge and Craigavon", false},
		{"GB", "ABD", "Aberdeenshire", false},
		{"GB", "ABE", "Aberdeen City", false},
		{"GB", "AGB", "Argyll and Bute", false},
		{"GB", "AGY", "Isle of Anglesey [Sir Ynys Mon GB-YNM]", false},
		{"GB", "AND", "North Down and Ards", false},
		{"GB", "ANN", "Antrim and Newtownabbey", false},
		{"GB", "ANS", "Angus", false},
		{"GB", "ANT", "Antrim", false}, //deleted 2015-11-27
		{"GB", "ARM", "Armagh", false},
		{"GB", "AVN", "Avon", false},
		{"GB", "BAS", "Bath and North East Somerset", false},
		{"GB", "BBD", "Blackburn with Darwen", false},
		{"GB", "BDF", "Bedfordshire", false},
		{"GB", "BFS", "Belfast (City of)", false},
		{"GB", "BGE", "Bridgend [Pen-y-bont ar Ogwr GB-POG]", false},
		{"GB", "BGW", "Blaenau Gwent", false},
		{"GB", "BIR", "Birmingham (City of)", false},
		{"GB", "BKM", "Buckinghamshire", false},
		{"GB", "BMH", "Bournemouth", false},
		{"GB", "BNH", "Brighton and Hove", false},
		{"GB", "BNS", "Barnsley", false},
		{"GB", "BOL", "Bolton", false},
		{"GB", "BPL", "Blackpool", false},
		{"GB", "BRC", "Bracknell Forest", false},
		{"GB", "BRD", "Bradford (City of)", false},
		{"GB", "BRK", "Berkshire", false},
		{"GB", "BST", "Bristol, City of", false},
		{"GB", "BUR", "Bury", false},
		{"GB", "CAM", "Cambridgeshire", false},
		{"GB", "CAY", "Caerphilly [Caerffili GB-CAF]", false},
		{"GB", "CBF", "Central Bedfordshire", false},
		{"GB", "CCG", "Causeway Coast and Glens", false},
		{"GB", "CGN", "Ceredigion [Sir Ceredigion]", false},
		{"GB", "CHE", "Cheshire East", false},
		{"GB", "CHS", "Cheshire", false},
		{"GB", "CHW", "Cheshire West and Chester", false},
		{"GB", "CLD", "Calderdale", false},
		{"GB", "CLK", "Clackmannanshire", false},
		{"GB", "CMA", "Cumbria", false},
		{"GB", "CMN", "Carmarthenshire [Sir Gaerfyrddin GB-GFY]", false},
		{"GB", "CON", "Cornwall", false},
		{"GB", "COV", "Coventry (City of)", false},
		{"GB", "CRF", "Cardiff (City of) [Caerdydd GB-CRD]", false},
		{"GB", "CWY", "Conwy", false},
		{"GB", "DAL", "Darlington", false},
		{"GB", "DBY", "Derbyshire", false},
		{"GB", "DEN", "Denbighshire [Sir Ddinbych GB-DDB]", false},
		{"GB", "DER", "Derby (City of)", false},
		{"GB", "DEV", "Devon", false},
		{"GB", "DGY", "Dumfries and Galloway", false},
		{"GB", "DNC", "Doncaster", false},
		{"GB", "DND", "Dundee City", false},
		{"GB", "DOR", "Dorset", false},
		{"GB", "DOW", "Down", false},
		{"GB", "DRS", "Derry and Strabane", false},
		{"GB", "DUD", "Dudley", false},
		{"GB", "DUR", "Durham", false},
		{"GB", "DVV", "Devon", false},
		{"GB", "EAY", "East Ayrshire", false},
		{"GB", "EDH", "Edinburgh, City of", false},
		{"GB", "EDU", "East Dunbartonshire", false},
		{"GB", "ELN", "East Lothian", false},
		{"GB", "ELS", "Eilean Siar", false},
		{"GB", "ERW", "East Renfrewshire", false},
		{"GB", "ERY", "East Riding of Yorkshire", false},
		{"GB", "ESS", "Essex", false},
		{"GB", "ESX", "East Sussex", false},
		{"GB", "FAL", "Falkirk", false},
		{"GB", "FIF", "Fife", false},
		{"GB", "FLN", "Flintshire [Sir y Fflint GB-FFL]", false},
		{"GB", "FMO", "Fermanagh and Omagh", false},
		{"GB", "GAT", "Gateshead", false},
		{"GB", "GLG", "Glasgow City", false},
		{"GB", "GLS", "Gloucestershire", false},
		{"GB", "GTL", "Greater London", false},
		{"GB", "GTM", "Greater Manchester", false},
		{"GB", "GWN", "Gwynedd", false},
		{"GB", "HAL", "Halton", false},
		{"GB", "HAM", "Hampshire", false},
		{"GB", "HEF", "Herefordshire", false},
		{"GB", "HLD", "Highland", false},
		{"GB", "HPL", "Hartlepool", false},
		{"GB", "HRT", "Hertfordshire", false},
		{"GB", "HUM", "Humberside", false},
		{"GB", "IOS", "Isles of Scilly", false},
		{"GB", "IOW", "Isle of Wight", false},
		{"GB", "IVC", "Inverclyde", false},
		{"GB", "JSY", "Jersey", false}, // OLD
		{"GB", "KEN", "Kent", false},
		{"GB", "KHL", "Kingston upon Hull, City of", false},
		{"GB", "KIR", "Kirklees", false},
		{"GB", "KWL", "Knowsley", false},
		{"GB", "LAN", "Lancashire", false},
		{"GB", "LBC", "Lisburn and Castlereagh", false},
		{"GB", "LCE", "Leicester (City of)", false},
		{"GB", "LDS", "Leeds (City of)", false},
		{"GB", "LEC", "Leicestershire", false},
		{"GB", "LIN", "Lincolnshire", false},
		{"GB", "LIV", "Liverpool (City of)", false},
		{"GB", "LND", "London, City of", false},
		{"GB", "LUT", "Luton", false},
		{"GB", "MAN", "Manchester (City of)", false},
		{"GB", "MDB", "Middlesbrough", false},
		{"GB", "MDW", "Medway", false},
		{"GB", "MEA", "Mid and East Antrim", false},
		{"GB", "MIK", "Milton Keynes", false},
		{"GB", "MLN", "Midlothian", false},
		{"GB", "MON", "Monmouthshire [Sir Fynwy GB-FYN]", false},
		{"GB", "MRY", "Moray", false},
		{"GB", "MSY", "Merseyside", false},
		{"GB", "MTY", "Merthyr Tydfil [Merthyr Tudful GB-MTU]", false},
		{"GB", "MUL", "Mid Ulster", false},
		{"GB", "NAY", "North Ayrshire", false},
		{"GB", "NBL", "Northumberland", false},
		{"GB", "NEL", "North East Lincolnshire", false},
		{"GB", "NET", "Newcastle upon Tyne (City of)", false},
		{"GB", "NFK", "Norfolk", false},
		{"GB", "NGM", "Nottingham (City of)", false},
		{"GB", "NLK", "North Lanarkshire", false},
		{"GB", "NLN", "North Lincolnshire", false},
		{"GB", "NMD", "Newry, Mourne and Down", false},
		{"GB", "NSM", "North Somerset", false},
		{"GB", "NTH", "Northamptonshire", false},
		{"GB", "NTL", "Neath Port Talbot [Castell-nedd Port Talbot GB-CTL]", false},
		{"GB", "NTT", "Nottinghamshire", false},
		{"GB", "NTY", "North Tyneside", false},
		{"GB", "NWP", "Newport [Casnewydd GB-CNW]", false},
		{"GB", "NYK", "North Yorkshire", false},
		{"GB", "OLD", "Oldham", false},
		{"GB", "ORK", "Orkney Islands", false},
		{"GB", "OXF", "Oxfordshire", false},
		{"GB", "PEM", "Pembrokeshire [Sir Benfro CB-BNF]", false},
		{"GB", "PKN", "Perth and Kinross", false},
		{"GB", "PLY", "Plymouth (City of)", false},
		{"GB", "POL", "Poole", false},
		{"GB", "POR", "Portsmouth (City of)", false},
		{"GB", "POW", "Powys", false},
		{"GB", "PTE", "Peterborough", false},
		{"GB", "RCC", "Redcar and Cleveland", false},
		{"GB", "RCH", "Rochdale", false},
		{"GB", "RCT", "Rhondda, Cynon, Taff [Rhondda, Cynon, Taf]", false},
		{"GB", "RDG", "Reading", false},
		{"GB", "RFW", "Renfrewshire", false},
		{"GB", "ROT", "Rotherham", false},
		{"GB", "RUT", "Rutland", false},
		{"GB", "SAW", "Sandwell", false},
		{"GB", "SAY", "South Ayrshire", false},
		{"GB", "SCB", "Scottish Borders, The", false},
		{"GB", "SEX", "", true},
		{"GB", "SFK", "Suffolk", false},
		{"GB", "SFT", "Sefton", false},
		{"GB", "SGC", "South Gloucestershire", false},
		{"GB", "SHF", "Sheffield (City of)", false},
		{"GB", "SHN", "St. Helens", false},
		{"GB", "SHR", "Shropshire", false},
		{"GB", "SKP", "Stockport", false},
		{"GB", "SLF", "Salford (City of)", false},
		{"GB", "SLG", "Slough", false},
		{"GB", "SLK", "South Lanarkshire", false},
		{"GB", "SND", "Sunderland (City of)", false},
		{"GB", "SOL", "Solihull", false},
		{"GB", "SOM", "Somerset", false},
		{"GB", "SOS", "Southend-on-Sea", false},
		{"GB", "SRY", "Surrey", false},
		{"GB", "STE", "Stoke-on-Trent (City of)", false},
		{"GB", "STG", "Stirling", false},
		{"GB", "STH", "Southampton (City of)", false},
		{"GB", "STS", "Staffordshire", false},
		{"GB", "STT", "Stockton-On-Tees", false},
		{"GB", "STY", "South Tyneside", false},
		{"GB", "SWA", "Swansea (City of) [Abertawe GB-ATA]", false},
		{"GB", "SWD", "Swindon", false},
		{"GB", "SYK", "South Yorkshire", false},
		{"GB", "TAM", "Tameside", false},
		{"GB", "TFW", "Telford and Wrekin", false},
		{"GB", "THR", "Thurrock", false},
		{"GB", "TOB", "Torbay", false},
		{"GB", "TOF", "Torfaen [Tor-faen]", false},
		{"GB", "TRF", "Trafford", false},
		{"GB", "TWR", "Tyne and Wear", false},
		{"GB", "VGL", "Vale of Glamorgan, The [Bro Morgannwg GB-BMG]", false},
		{"GB", "WAR", "Warwickshire", false},
		{"GB", "WBK", "West Berkshire", false},
		{"GB", "WDU", "West Dunbartonshire", false},
		{"GB", "WGN", "Wigan", false},
		{"GB", "WIL", "Wiltshire", false},
		{"GB", "WKF", "Wakefield (City of)", false},
		{"GB", "WLL", "Walsall", false},
		{"GB", "WLN", "West Lothian", false},
		{"GB", "WLV", "Wolverhampton", false},
		{"GB", "WMD", "West Midlands", false},
		{"GB", "WNM", "Windsor and Maidenhead", false},
		{"GB", "WOK", "Wokingham", false},
		{"GB", "WOR", "Worcestershire", false},
		{"GB", "WRL", "Wirral", false},
		{"GB", "WRT", "Warrington", false},
		{"GB", "WRX", "Wrexham [Wrecsam GB-WRC]", false},
		{"GB", "WSX", "West Sussex", false},
		{"GB", "WYK", "West Yorkshire", false},
		{"GB", "YOR", "York (City of)", false},
		{"GB", "ZET", "Shetland Islands", false},

		{"IE", "", "Ireland", false},

		{"IE", "C", "Connaught (Connacht)", false},
		{"IE", "L", "Leinster (Laighin)", false},
		{"IE", "M", "Munster (An Mhumhain)", false},
		{"IE", "U", "Ulster (Ulaidh)", false},

		{"IE", "CW", "Carlow (Ceatharlach)", false},
		{"IE", "CN", "Cavan (An Cabhán)", false},
		{"IE", "CE", "Clare (An Clár)", false},
		{"IE", "CO", "Cork (Corcaigh)", false},
		{"IE", "DL", "Donegal (Dún na nGall)", false},
		{"IE", "D", "Dublin (Baile Átha Cliath)", false},
		{"IE", "G", "Galway (Gaillimh)", false},
		{"IE", "KY", "Kerry (Ciarraí)", false},
		{"IE", "KE", "Kildare (Cill Dara)", false},
		{"IE", "KK", "Kilkenny (Cill Chainnigh)", false},
		{"IE", "LS", "Laois (Laois)", false},
		{"IE", "LM", "Leitrim (Liatroim)", false},
		{"IE", "LK", "Limerick (Luimneach)", false},
		{"IE", "LD", "Longford (An Longfort)", false},
		{"IE", "LH", "Louth (Lú)", false},
		{"IE", "MO", "Mayo (Maigh Eo)", false},
		{"IE", "MH", "Meath (An Mhí)", false},
		{"IE", "MN", "Monaghan (Muineachán)", false},
		{"IE", "OY", "Offaly (Uíbh Fhailí)", false},
		{"IE", "RN", "Roscommon (Ros Comáin)", false},
		{"IE", "SO", "Sligo (Sligeach)", false},
		{"IE", "TA", "Tipperary (Tiobraid Árann)", false},
		{"IE", "WD", "Waterford (Port Láirge)", false},
		{"IE", "WH", "Westmeath (An Iarmhí)", false},
		{"IE", "WX", "Wexford (Loch Garman)", false},
		{"IE", "WW", "Wicklow (Cill Mhantáin)", false},

		// extra:
		{"GB", "E", "London East", false},
		{"GB", "TSS", "Teesside", false},
	}

	for _, test := range tests {
		if actual, err := Decode(test.Country, test.Region, true); actual != test.Expected || test.ExpectError != (err != nil) {
			t.Errorf("iso3166.Decode(%q, %q) gave %q but wanted %q: %s", test.Country, test.Region, actual, test.Expected, err)
		}
	}
}
